version: '3'

services:
  app:
    image: 'boilerplate-react-native'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: 'development'
        NODE_CONFIG_ENV: 'development'
    environment:
      NODE_APP_INSTANCE: 'docker'
    command: 'yarn test'
