version: '3'

services:
  app:
    platform: 'linux/amd64'
    image: 'boilerplate-react-native'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: 'development'
    environment:
      NODE_ENV: 'development'
      NODE_APP_INSTANCE: 'docker'
    command: 'yarn start'
    ports:
      - '3000:3000'
    volumes:
      - './:/app:delegated'
      - '/app/node_modules/'
    working_dir: /opt/app
