# name: android_deploy_to_production

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]

#   # push:
#   #   branches:
#   #     - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     outputs:
#       image_ref: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/boilerplate-react-native@${{ steps.build.outputs.image_digest }}
#     steps:
#       - name: Checkout (app)
#         uses: actions/checkout@v3
#         # make sure to keep checked in code at different directory to avoid colliding with docker caching
#         with:
#           path: app

#       - name: Extract branch name
#         id: extract_branch
#         shell: bash
#         run: |
#           BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }} | sed -e 's/^refs\/heads\///g')
#           BRANCH_HASH=$(sha1sum < <(printf '%s' $BRANCH_NAME) | cut -c -15)

#           echo "##[set-output name=branch_hash;]$(echo $BRANCH_HASH)"

#       - name: Build application
#         id: build
#         uses: ./app/.github/actions/build
#         with:
#           tags: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/boilerplate-react-native:${{ steps.extract_branch.outputs.branch_hash }}
#           build_args: NODE_CONFIG_ENV=production
#           build_secrets: ''
#           context: app/
#           docker_registry: ${{ vars.DOCKER_REGISTRY }}
#           docker_username: ${{ vars.DOCKER_USERNAME }}
#           docker_password: ${{ secrets.DOCKER_PASSWORD }}
  
#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps: 
#       - uses: build 
#       - name: Decrypt Android keys 
#         run: sh ./.github/scripts/decrypt_android_keys.sh 
#         env: 
#           RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
#           RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
#           SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
#           SERVICE_ACCOUNT_PASSPHRASE: ${{ secrets.SERVICE_ACCOUNT_PASSPHRASE }}

#       - name: Upload to PlayStore 
#         run: | 
#             cd android 
#             fastlane android release_production RELEASE_KEYSTORE_PASSWORD:${{secrets.RELEASE_KEYSTORE_PASSWORD}} RELEASE_KEYSTORE_KEY_PASSWORD:${{secrets.RELEASE_KEYSTORE_KEY_PASSWORD}} RELEASE_KEYSTORE_ALIAS:${{secrets.RELEASE_KEYSTORE_ALIAS}}
   
