name: production_on_push

on:
  push:
    branches:
      - main

jobs:
  # sonarqube:
  #   name: analyze
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         # Disabling shallow clone is recommended for improving relevancy of reporting
  #         fetch-depth: 0
      
  #     - name: sonarqube-scan-branch
  #       uses: sonarsource/sonarqube-scan-action@master
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  #       with:
  #         args: >
  #           -Dsonar.branch.name=${{ github.event.ref }}

  checks:
    runs-on: ubuntu-latest
    strategy:
      # turn off fail fast, let all the checks run irrespective of failures
      fail-fast: false
      matrix:
        check: ['yarn:lint', 'compose:test']
    steps:
      - name: Checkout (app)
        uses: actions/checkout@v2
        # with:
        #   path: app
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      # - uses: ruby/setup-ruby@v1
      #   with:
      #    ruby-version: '3.1.2'

      # - name: Install Fastlane
      #   run: cd android && bundle install && cd ..

      - name: Install packages
        run: yarn install

      - name: Run check
        uses: ./.github/actions/check
        with:
          check: ${{ matrix.check }}

  deploy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'

    - name: Install Fastlane
      run: cd android && bundle install && cd ..

    - name: Install packages
      run: yarn install

    - name: Decrypt Android keys
      env: 
        RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
        RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
        RELEASE_KEYSTORE_KEY_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_KEY_PASSWORD }}
        RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
      run: |
        mkdir -p android/fastlane/config
        echo "$RELEASE_KEYSTORE" > upload-keystore.jks.asc
        gpg -d --passphrase="$RELEASE_KEYSTORE_PASSPHRASE" --batch upload-keystore.jks.asc > android/fastlane/config/upload-keystore.jks
       
    - name: Upload to PlayStore 
      run: cd android && fastlane android release_production RELEASE_KEYSTORE_PASSWORD:${{secrets.RELEASE_KEYSTORE_PASSWORD}} RELEASE_KEYSTORE_KEY_PASSWORD:${{secrets.RELEASE_KEYSTORE_KEY_PASSWORD}} RELEASE_KEYSTORE_ALIAS:${{secrets.RELEASE_KEYSTORE_ALIAS}}